/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2021-02-21 20:07:19 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:15432/dvdrental -t customer_list -t nicer_but_slower_film_list -t film -t customer -t actor -t city -t sales_by_film_category -t film_list -t address -t inventory -t staff -t country -t rental -t film_actor -t sales_by_store -t film_category -t store -t staff_list -t language -t payment -t category -t actor_info -s public
 *
 */

export type mpaa_rating = 'G' | 'NC-17' | 'PG' | 'PG-13' | 'R';

export namespace customer_listFields {
    export type id = number | null;
    export type name = string | null;
    export type address = string | null;
    export type postal_code = string | null;
    export type phone = string | null;
    export type city = string | null;
    export type country = string | null;
    export type notes = string | null;
    export type sid = number | null;

}

export interface customer_list {
    id: customer_listFields.id;
    name: customer_listFields.name;
    address: customer_listFields.address;
    postal_code: customer_listFields.postal_code;
    phone: customer_listFields.phone;
    city: customer_listFields.city;
    country: customer_listFields.country;
    notes: customer_listFields.notes;
    sid: customer_listFields.sid;

}

export namespace nicer_but_slower_film_listFields {
    export type fid = number | null;
    export type title = string | null;
    export type description = string | null;
    export type category = string | null;
    export type price = number | null;
    export type length = number | null;
    export type rating = mpaa_rating | null;
    export type actors = string | null;

}

export interface nicer_but_slower_film_list {
    fid: nicer_but_slower_film_listFields.fid;
    title: nicer_but_slower_film_listFields.title;
    description: nicer_but_slower_film_listFields.description;
    category: nicer_but_slower_film_listFields.category;
    price: nicer_but_slower_film_listFields.price;
    length: nicer_but_slower_film_listFields.length;
    rating: nicer_but_slower_film_listFields.rating;
    actors: nicer_but_slower_film_listFields.actors;

}

export namespace filmFields {
    export type film_id = number;
    export type title = string;
    export type description = string | null;
    export type release_year = number | null;
    export type language_id = number;
    export type rental_duration = number;
    export type rental_rate = number;
    export type length = number | null;
    export type replacement_cost = number;
    export type rating = mpaa_rating | null;
    export type last_update = Date;
    export type special_features = Array<string> | null;
    export type fulltext = any;

}

export interface film {
    film_id: filmFields.film_id;
    title: filmFields.title;
    description: filmFields.description;
    release_year: filmFields.release_year;
    language_id: filmFields.language_id;
    rental_duration: filmFields.rental_duration;
    rental_rate: filmFields.rental_rate;
    length: filmFields.length;
    replacement_cost: filmFields.replacement_cost;
    rating: filmFields.rating;
    last_update: filmFields.last_update;
    special_features: filmFields.special_features;
    fulltext: filmFields.fulltext;

}

export namespace customerFields {
    export type customer_id = number;
    export type store_id = number;
    export type first_name = string;
    export type last_name = string;
    export type email = string | null;
    export type address_id = number;
    export type activebool = boolean;
    export type create_date = Date;
    export type last_update = Date | null;
    export type active = number | null;

}

export interface customer {
    customer_id: customerFields.customer_id;
    store_id: customerFields.store_id;
    first_name: customerFields.first_name;
    last_name: customerFields.last_name;
    email: customerFields.email;
    address_id: customerFields.address_id;
    activebool: customerFields.activebool;
    create_date: customerFields.create_date;
    last_update: customerFields.last_update;
    active: customerFields.active;

}

export namespace actorFields {
    export type actor_id = number;
    export type first_name = string;
    export type last_name = string;
    export type last_update = Date;

}

export interface actor {
    actor_id: actorFields.actor_id;
    first_name: actorFields.first_name;
    last_name: actorFields.last_name;
    last_update: actorFields.last_update;

}

export namespace cityFields {
    export type city_id = number;
    export type city = string;
    export type country_id = number;
    export type last_update = Date;

}

export interface city {
    city_id: cityFields.city_id;
    city: cityFields.city;
    country_id: cityFields.country_id;
    last_update: cityFields.last_update;

}

export namespace sales_by_film_categoryFields {
    export type category = string | null;
    export type total_sales = number | null;

}

export interface sales_by_film_category {
    category: sales_by_film_categoryFields.category;
    total_sales: sales_by_film_categoryFields.total_sales;

}

export namespace film_listFields {
    export type fid = number | null;
    export type title = string | null;
    export type description = string | null;
    export type category = string | null;
    export type price = number | null;
    export type length = number | null;
    export type rating = mpaa_rating | null;
    export type actors = string | null;

}

export interface film_list {
    fid: film_listFields.fid;
    title: film_listFields.title;
    description: film_listFields.description;
    category: film_listFields.category;
    price: film_listFields.price;
    length: film_listFields.length;
    rating: film_listFields.rating;
    actors: film_listFields.actors;

}

export namespace addressFields {
    export type address_id = number;
    export type address = string;
    export type address2 = string | null;
    export type district = string;
    export type city_id = number;
    export type postal_code = string | null;
    export type phone = string;
    export type last_update = Date;

}

export interface address {
    address_id: addressFields.address_id;
    address: addressFields.address;
    address2: addressFields.address2;
    district: addressFields.district;
    city_id: addressFields.city_id;
    postal_code: addressFields.postal_code;
    phone: addressFields.phone;
    last_update: addressFields.last_update;

}

export namespace inventoryFields {
    export type inventory_id = number;
    export type film_id = number;
    export type store_id = number;
    export type last_update = Date;

}

export interface inventory {
    inventory_id: inventoryFields.inventory_id;
    film_id: inventoryFields.film_id;
    store_id: inventoryFields.store_id;
    last_update: inventoryFields.last_update;

}

export namespace staffFields {
    export type staff_id = number;
    export type first_name = string;
    export type last_name = string;
    export type address_id = number;
    export type email = string | null;
    export type store_id = number;
    export type active = boolean;
    export type username = string;
    export type password = string | null;
    export type last_update = Date;
    export type picture = string | null;

}

export interface staff {
    staff_id: staffFields.staff_id;
    first_name: staffFields.first_name;
    last_name: staffFields.last_name;
    address_id: staffFields.address_id;
    email: staffFields.email;
    store_id: staffFields.store_id;
    active: staffFields.active;
    username: staffFields.username;
    password: staffFields.password;
    last_update: staffFields.last_update;
    picture: staffFields.picture;

}

export namespace countryFields {
    export type country_id = number;
    export type country = string;
    export type last_update = Date;

}

export interface country {
    country_id: countryFields.country_id;
    country: countryFields.country;
    last_update: countryFields.last_update;

}

export namespace rentalFields {
    export type rental_id = number;
    export type rental_date = Date;
    export type inventory_id = number;
    export type customer_id = number;
    export type return_date = Date | null;
    export type staff_id = number;
    export type last_update = Date;

}

export interface rental {
    rental_id: rentalFields.rental_id;
    rental_date: rentalFields.rental_date;
    inventory_id: rentalFields.inventory_id;
    customer_id: rentalFields.customer_id;
    return_date: rentalFields.return_date;
    staff_id: rentalFields.staff_id;
    last_update: rentalFields.last_update;

}

export namespace film_actorFields {
    export type actor_id = number;
    export type film_id = number;
    export type last_update = Date;

}

export interface film_actor {
    actor_id: film_actorFields.actor_id;
    film_id: film_actorFields.film_id;
    last_update: film_actorFields.last_update;

}

export namespace sales_by_storeFields {
    export type store = string | null;
    export type manager = string | null;
    export type total_sales = number | null;

}

export interface sales_by_store {
    store: sales_by_storeFields.store;
    manager: sales_by_storeFields.manager;
    total_sales: sales_by_storeFields.total_sales;

}

export namespace film_categoryFields {
    export type film_id = number;
    export type category_id = number;
    export type last_update = Date;

}

export interface film_category {
    film_id: film_categoryFields.film_id;
    category_id: film_categoryFields.category_id;
    last_update: film_categoryFields.last_update;

}

export namespace storeFields {
    export type store_id = number;
    export type manager_staff_id = number;
    export type address_id = number;
    export type last_update = Date;

}

export interface store {
    store_id: storeFields.store_id;
    manager_staff_id: storeFields.manager_staff_id;
    address_id: storeFields.address_id;
    last_update: storeFields.last_update;

}

export namespace staff_listFields {
    export type id = number | null;
    export type name = string | null;
    export type address = string | null;
    export type postal_code = string | null;
    export type phone = string | null;
    export type city = string | null;
    export type country = string | null;
    export type sid = number | null;

}

export interface staff_list {
    id: staff_listFields.id;
    name: staff_listFields.name;
    address: staff_listFields.address;
    postal_code: staff_listFields.postal_code;
    phone: staff_listFields.phone;
    city: staff_listFields.city;
    country: staff_listFields.country;
    sid: staff_listFields.sid;

}

export namespace languageFields {
    export type language_id = number;
    export type name = string;
    export type last_update = Date;

}

export interface language {
    language_id: languageFields.language_id;
    name: languageFields.name;
    last_update: languageFields.last_update;

}

export namespace paymentFields {
    export type payment_id = number;
    export type customer_id = number;
    export type staff_id = number;
    export type rental_id = number;
    export type amount = number;
    export type payment_date = Date;

}

export interface payment {
    payment_id: paymentFields.payment_id;
    customer_id: paymentFields.customer_id;
    staff_id: paymentFields.staff_id;
    rental_id: paymentFields.rental_id;
    amount: paymentFields.amount;
    payment_date: paymentFields.payment_date;

}

export namespace categoryFields {
    export type category_id = number;
    export type name = string;
    export type last_update = Date;

}

export interface category {
    category_id: categoryFields.category_id;
    name: categoryFields.name;
    last_update: categoryFields.last_update;

}

export namespace actor_infoFields {
    export type actor_id = number | null;
    export type first_name = string | null;
    export type last_name = string | null;
    export type film_info = string | null;

}

export interface actor_info {
    actor_id: actor_infoFields.actor_id;
    first_name: actor_infoFields.first_name;
    last_name: actor_infoFields.last_name;
    film_info: actor_infoFields.film_info;

}
